_FONT_FAMILY = "Calibri"
MAIN_FONT = (_FONT_FAMILY, 12)
HEADING_FONT = (_FONT_FAMILY, 16, "bold")

NAVY_BLUE = "#0A2342"
WARM_CREAM = "#FFFDD0"
MUTED_GOLD = "#B08D57"

BUTTON_COLOR = NAVY_BLUE
BUTTON_TEXT_COLOR = WARM_CREAM

PRIMARY_COLOR = NAVY_BLUE
SECONDARY_COLOR = MUTED_GOLD
BACKGROUND_COLOR = WARM_CREAM

LABEL_COLOR = NAVY_BLUE
TEXT_COLOR = NAVY_BLUE
LIGHT_TEXT_COLOR = WARM_CREAM

ERROR_COLOR = "#C82333"
SUCCESS_COLOR = "#218838"